version: "3"
services:
  server:
    container_name: server
    env_file:
      - ./server/.env
    build: ./server
    ports:
      - "8080:8080"
      - "5432:5432"
    restart: unless-stopped

  client:
    container_name: client
    env_file:
      - ./client/.env
    depends_on:
      - server
    links:
      - "server:server"
    build: ./client
    restart: unless-stopped
    ports:
      - "80:80"
