version: "3"
services:
  database:
    container_name: database
    image: "postgres"
    env_file:
      - ./server/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U all_user -d all_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    container_name: server
    depends_on:
      database:
        condition: "service_healthy"
    env_file:
      - ./server/.env
    links:
      - "database:database"
    build: ./server
    ports:
      - "5005:5005"
    restart: unless-stopped

  client:
    container_name: client
    env_file:
      - ./client/.env
    depends_on:
      - server
    links:
      - "server:server"
    build: ./client
    restart: unless-stopped
    ports:
      - "443:443"

volumes:
  db-data:
