const LAB_ID = 12;
const REPAIR = "/Repair";
const EXERCISE_PATH = "/Lab12/Exercise";

const IDENTITY_REPAIR_HEADING = "Identity Repair";
const EXERCISE_SELECTION_DEFAULT = "IdentityRepair";

const EXERCISE_STATES = {
  EXERCISE_SELECTION_DEFAULT,
};

export {
  LAB_ID,
  REPAIR,
  EXERCISE_PATH,
  IDENTITY_REPAIR_HEADING,
  EXERCISE_SELECTION_DEFAULT,
  EXERCISE_STATES,
};
