export const danMockData = [
	{
		"id": 1,
		"name": "Dan Me",
		src: '/img/profileImages/Professor_Krutz.jpg',
		'gender': 'M',
		'age': 100,
		'years': 10,
		'availability': 'Yes',
		'pay': 10000,
		'ai': 'false',
	},
	{
		"id": 2,
		"name": "Dan Me",
		'gender': 'M',
		src: '/img/profileImages/Professor_Krutz.jpg',
		'age': 100,
		'years': 10,
		'availability': 'Yes',
		'pay': 10000,
		'ai': 'false',
	},
	{
		"id": 3,
		"name": "Dan Me",
		src: '/img/profileImages/Professor_Krutz.jpg',
		'gender': 'M',
		'age': 100,
		'years': 10,
		'availability': 'Yes',
		'pay': 10000,
		'ai': 'false',
	},
	{
		"id": 4,
		"name": "Dan Me",
		src: '/img/profileImages/Professor_Krutz.jpg',
		'gender': 'M',
		'age': 100,
		'years': 10,
		'availability': 'Yes',
		'pay': 10000,
		'ai': 'false',
	},
]