const LAB_ID = 16;
const EXERCISE_PATH = "/Lab16/Exercise";

const EXERCISE_SELECTION_DEFAULT = "default selection";

const EXERCISE_STATES = {
  EXERCISE_SELECTION_DEFAULT,
};

export { LAB_ID, EXERCISE_PATH, EXERCISE_STATES };