server {
    listen       80;
    server_name  all.rit.edu;

    location / {
        root /var/www/html;
        index index.html index.htm;
        try_files $uri $uri/ $uri.html /index.html =404;
    }
    
    location /api/ {
        proxy_pass http://server:5005;
    }
}