server {
    listen 80;
    server_name _;
    return 301 https://all.rit.edu$request_uri;
}

server {
    listen                  443 ssl;
    server_name             all.rit.edu;
    ssl_certificate         /etc/letsencrypt/live/all.rit.edu/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/all.rit.edu/privkey.pem;
    ssl_protocols           TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers             HIGH:!aNULL:!MD5;

    root /var/www/html;
    index index.html index.htm;
    try_files $uri $uri/ $uri.html /index.html =404;
}
