const LAB_ID = 11;
const EXERCISE_PLAYING = "EXERCISE_PLAYING";
const EXERCISE_IDLE = "EXERCISE_IDLE";

const EXERCISE_STATES = {};

export { LAB_ID, EXERCISE_PLAYING, EXERCISE_IDLE, EXERCISE_STATES };
