const EXERCISE_SELECTION_DEFAULT = "default";
const EXERCISE_SELECTION_WRITE = "write-lab";
const EXERCISE_SELECTION_DEVELOP = "develop-lab";

const SELECTION_ROUTE = "/";
const DESIGN_LAB_INTRO = "DesignLabIntro";
const SCRUM_INTRO = "ScrumIntroduction";
const DEVELOP_LAB_INTRO = "DevelopLabIntro";
const SCRUM_BOARD_ACTIVITY = "ScrumBoardActivity";

const ROUTES = {
  SELECTION_ROUTE,
  DESIGN_LAB_INTRO,
  DEVELOP_LAB_INTRO,
  SCRUM_INTRO,
  SCRUM_BOARD_ACTIVITY,
};

const EXERCISE_STATES = {
  EXERCISE_SELECTION_DEFAULT,
  EXERCISE_SELECTION_WRITE,
  EXERCISE_SELECTION_DEVELOP,
};

export { EXERCISE_STATES, ROUTES };
