// const SECTION_CATEGORY_DESIGN = "DESIGN";
const SECTION_CATEGORY_BACKEND = "BACKEND";
// const SECTION_CATEGORY_FRONTEND = "FRONTEND";

const SECTION_LAB_DATA_REPAIR = "LabDataRepair";

const SECTION_IN_PROGRESS = "IN_PROGRESS";
const SECTION_COMPLETED = "COMPLETED";

const ROUTES = {
  SECTION_LAB_DATA_REPAIR,
};

const SECTIONS = {
  SECTION_LAB_DATA_REPAIR: {
    category: SECTION_CATEGORY_BACKEND,
    name: SECTION_LAB_DATA_REPAIR,
  },
};

const SECTION_STATUSES = {
  SECTION_IN_PROGRESS,
  SECTION_COMPLETED,
};

export { ROUTES, SECTIONS, SECTION_STATUSES };
