const EXERCISE_SELECTION_DEFAULT = "default";
const EXERCISE_SELECTION_WRITE = "write-lab";
const EXERCISE_SELECTION_DEVELOP = "develop-lab";

const SELECTION_ROUTE = "/";
const WRITE_LAB_INTRO = "WriteLabIntro";
const DEVELOP_LAB_INTRO = "DevelopLabIntro";

const ROUTES = {
  SELECTION_ROUTE,
  WRITE_LAB_INTRO,
  DEVELOP_LAB_INTRO,
};

const EXERCISE_STATES = {
  EXERCISE_SELECTION_DEFAULT,
  EXERCISE_SELECTION_WRITE,
  EXERCISE_SELECTION_DEVELOP,
};

export { EXERCISE_STATES, ROUTES };
