const LAB_ID = 9;
const START_PATH = "/*";
const EXERCISE_SELECTION = "/Exercise";
const REPAIR = "/GameRepair";

const REPAIR_ADDRESS_FORM = "ADDRESS_REPAIR";
const REPAIR_DATE_REPAIR = "REPAIR_DATE";
const REPAIR_NAV_BAR = "NAV_BAR_REPAIR";
const EXERCISE_SELECTION_DEFAULT = "selection";

const GAME_STATES = {
  REPAIR_ADDRESS_FORM,
  REPAIR_DATE_REPAIR,
  REPAIR_NAV_BAR,
  EXERCISE_SELECTION_DEFAULT,
};

export { LAB_ID, START_PATH, EXERCISE_SELECTION, REPAIR, GAME_STATES };
