const LAB_ID = 9;
const START_PATH = "/*";
const EXERCISE_SELECTION = "/Exercise";
const REPAIR = "/GameRepair";

const REPAIR_ADDRESS_FORM = "ADDRESS_REPAIR";
const REPAIR_DATE_REPAIR = "REPAIR_DATE";
const NAV_BAR_REPAIR = "NAV_BAR_REPAIR";
const EXERCISE_SELECTION_DEFAULT = "selection";

const GAME_STATES = {
  REPAIR_ADDRESS_FORM,
  REPAIR_DATE_REPAIR,
  NAV_BAR_REPAIR,
};

export {
  LAB_ID,
  START_PATH,
  EXERCISE_SELECTION,
  EXERCISE_SELECTION_DEFAULT,
  REPAIR,
  GAME_STATES,
};
