export const UPDATE_CODE = 'UPDATE_CODE';
export const UPDATE_CORRECT_BACKGROUND = 'UPDATE_CORRECT_BACKGROUND';
export const UPDATE_INCORRECT_BACKGROUND = 'UPDATE_INCORRECT_BACKGROUND';
export const RESET_CODE = 'RESET_CODE';
export const UPDATE_CODE_EDITOR_STATUS = 'UPDATE_CODE_EDITOR_STATUS';
export const UPDATE_TAB = 'UPDATE_TAB';
