#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd client
npx prettier --write .

npx prettier --check .

eslint --fix .

echo eslint .

echo "All Client tests passed!"

cd ../server
eslint --fix .
echo eslint .

echo "ALL Server tests passed!"

npx pretty-quick --staged