name: Continuous Deployment
on:
  push:
    branches: ['docker-deploy']

jobs:
  deploy_job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        HOST: ec2-34-239-168-20.compute-1.amazonaws.com
        USERNAME: ubuntu
        PORT: 22
        KEY: ${{ secrets.TEST_ENV_KEY }}
        source: "."
        target: "/home/ubuntu/ALL/"
    - name: Restarting Docker Stack
      uses: appleboy/ssh-action@master
      with:
        HOST: ec2-34-239-168-20.compute-1.amazonaws.com
        USERNAME: ubuntu
        PORT: 22
        KEY: ${{ secrets.TEST_ENV_KEY }}
        script: |
          cd ALL
          docker-compose down
          docker-compose up --build -d
