name: Continuous Deployment
on:
  push:
    branches: ['master']
    paths:
      - 'client/**'
      - 'server/**'
      - 'docker-compose.yml'


jobs:
  deploy_job:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        HOST: all.rit.edu
        USERNAME: all
        PORT: 22
        KEY: ${{ secrets.SSH_SECRET }}
        source: "."
        target: "/home/all/research/"
    - name: Restarting Docker Stack
      uses: appleboy/ssh-action@master
      with:
        HOST: all.rit.edu
        USERNAME: all
        PORT: 22
        KEY: ${{ secrets.SSH_SECRET }}
        script: |
          cd research
          docker-compose down
          docker image prune -a
          docker-compose up --build -d
