name: Production-Deployment
on:
  pull_request:
    types:
      - closed
    branches:
      - prod
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo The PR was merged
  run_build:
    name: client-server build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: cd client
      - run: npm i --legacy-peer-deps
      - run: npm run build --if-present
      - run: cd ../
      - run: cd server
      - run: npm i
      - run: npm run build --if-present
  run_server_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: removes existing modules
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_NAME }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_SECRET }}
          port: ${{ secrets.PORT }}
          script: |
            ${{ secrets.CD_SERVER }}
            npm cache clean --force
            rm -rf node_modules
            rm package-lock.json
      - name: installs server dependencies to production
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_NAME }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_SECRET }}
          port: ${{ secrets.PORT }}
          script: |
            ${{ secrets.CD_SERVER }}
            npm i -verbose --legacy-peer-deps
      - name: Kickstart process management
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_NAME }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_SECRET }}
          port: ${{ secrets.PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            ${{ secrets.PM2 }} delete all
            ${{ secrets.PM2 }} start
  run_client_deploy:
    needs: run_server_deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: clone repository to deploy action
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: echo ${{ secrets.PROD_ENV }} > ./client/.env
      - run: |
          cd client
          npm i --legacy-peer-deps 
          npm run build --verbose
      - name: delete build and create new
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_NAME }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_SECRET }}
          port: ${{ secrets.PORT }}
          script: |
            cd research/client
            rm -rf build
            mkdir ../build
      - name: Run a multi-line script
        run: |
          cp -TR . ../build
          tar -cvf deploy.tar ../build/
      - name: scp build directory
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST_NAME }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_SECRET }}
          port: ${{ secrets.PORT }}
          source: "deploy.tar"
          target: ${{ secrets.CD_CLIENT }}
      - name: Unzip build directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_NAME }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_SECRET }}
          port: ${{ secrets.PORT }}
          script: |
            ${{ secrets.CD_SERVER }}
            tar -xvzf deploy.tar -C ./build
      - name: delete zipDeploy directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_NAME }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_SECRET }}
          port: ${{ secrets.PORT }}
          script: |
            ${{ secrets.CD_SERVER }}
            rm deploy.tar
