# This workflow does a clean installation of node dependencies, caches them, and builds the client and server.
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: ["prod", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Build client
        run: |
          cd client
          npm i --legacy-peer-deps
          npm run build --if-present
      - name: Build server
        run: |
          cd server
          npm i --legacy-peer-deps
          npm run build --if-present
